#pragma once

#define TokensList \
	TOKEN(ErrorToken) \
	TOKEN(SpecialSymbolToken) \
	TOKEN(IntegerToken) \
	TOKEN(DecimalToken) \
	TOKEN(AdditionOperatorToken) \
	TOKEN(SubtractionOperatorToken) \
	TOKEN(MultiplicationOperatorToken) \
	TOKEN(DivisionOperatorToken) \
	TOKEN(RemainderOperatorToken) \
	TOKEN(OpenedBracketToken) \
	TOKEN(ClosedBracketToken) \

typedef enum
{
#define TOKEN(TokenName) TokenName,
	TokensList
#undef TOKEN
}TokenType;

/// <summary>
/// The Token structure generated by the lexer to be used in the parser
/// </summary>
typedef struct
{
	TokenType tokenType;
	char* valuePtr;
	size_t length;
} Token;
