#pragma once
#include "../Parser/ASTNode.h"
#include "../LexerParserShared/Position.h"

// Defines a list of tokens used in the lexer/parser.
// Format:
//     TOKEN(TokenName, AST_NodeType, TokenCategory)
// 
// Notes:
// - Use `-1` as the category only for tokens that will NOT be passed to the parser.
//   These are typically special or error tokens handled in the lexer itself.
//
// AST_NodeType in each TOKEN indicates the AST node type the token will map to after being parsed.
// Token categories (like ValueTokenCategory, OperatorTokenCategory) are defined separately in TokenTypeCategory enum. 
// 
// If a token belongs to a category that does not handle its associated NodeType, 
// it will either be ignored or cause a parsing error.
// 
// Tokens like OpenedBracketToken are handled structurally in the parser and do not produce AST nodes (mapped to NoneNodeType).
#define TokensList \
	TOKEN(Error,                  NoneNodeType,             -1)                     /* Used when token creation fails */ \
	TOKEN(Special,                NoneNodeType,             -1)                     /* Specially handled (e.g. identifiers, numbers) */ \
	/* Value Tokens */ \
	TOKEN(Integer,                IntegerNodeType,          ValueTokenCategory)     \
	TOKEN(Decimal,                DecimalNodeType,          ValueTokenCategory)     \
	/* Operator Tokens */ \
	TOKEN(AdditionOperator,       AdditionNodeType,         OperatorTokenCategory)  \
	TOKEN(SubtractionOperator,    SubtractionNodeType,      OperatorTokenCategory)  \
	TOKEN(MultiplicationOperator, MultiplicationNodeType,   OperatorTokenCategory)  \
	TOKEN(DivisionOperator,       DivisionNodeType,         OperatorTokenCategory)  \
	TOKEN(RemainderOperator,      RemainderNodeType,        OperatorTokenCategory)  \
	TOKEN(PowerOperator,		  PowerNodeType,        OperatorTokenCategory)  \
	/* Bracket Tokens */ \
	TOKEN(OpenedBracket,          NoneNodeType,             BracketTokenCategory)   \
	TOKEN(ClosedBracket,          NoneNodeType,             BracketTokenCategory)   \

typedef enum TokenTypeCategory TokenTypeCategory;
enum TokenTypeCategory
{
	ValueTokenCategory ,
	OperatorTokenCategory,
	BracketTokenCategory,
	TokenTypeCategory_Count //This should always be the last one.
};

typedef enum TokenType TokenType;
enum TokenType
{
#define TOKEN(TokenName , NodeType , TokenTypeCategory) TokenName##Token,
	TokensList
#undef TOKEN
	TokenType_Count // Should always be the last one.
};

//Maps Every TokenType to its corresponding category .
extern const TokenTypeCategory tokenTypeCategoryTable[ TokenType_Count ];
const TokenTypeCategory GetTokenCategory ( TokenType tokenType );


//Maps Every TokenType to its corresponding NodeType .
extern const ASTNodeType tokenType_NodeType_Table[ TokenType_Count ];
ASTNodeType GetTokenNodeType ( TokenType tokenType );

// The Token structure generated by the lexer to be used in the parser.
typedef struct Token Token;
struct Token
{
	TokenType tokenType;

	//The string value of the token.
	const char* valuePtr;
	//The length of the token string.
	size_t length;

	Position position;
};

typedef struct TokenArray TokenArray;
struct TokenArray
{
	Token* tokens;
	size_t length;
};

Token CreateToken ( TokenType type , const  char* valuePtr , size_t length , Position position );